### ISSUE TITLE
chromium-ozone-wayland: version 90.0.4430.93 can cause desktop Black screen some times

### ISSUE THREAD

**Issue by jwzl** [OSSystems/meta-browser#525] opened 2021-07-16 01:22 UTC
When I updated chromium to  90.0.4430.93,  chromium can cause desktop Black screen at some times. When I restart the weston , the desktop show well. it's seems has no more error message?
Do you know what cause this issue?

**Comment by msisov** [comment] 2021-07-19 08:01
The issue is known and has already been fixed in the upstream. Please refer to https://chromium-review.googlesource.com/c/chromium/src/+/2805521 . The patch is part of M92 stable release, which Google releases tomorrow. So, you can expect the recipe to be updated to M92 during this or next week at the latest.

While this patch doesn't mention that specific problem explicitly (my colleague fixed another issue that was introduced by the patches that enabled rounded corners), this patch indeed fixes the problem. This was just the way how the problem of placing an entire frame into an aggregate frame behaves on imx8.

**Closed by msisov** 2021-07-19 08:01 UTC
